project:
  type: website

website:
  description: "Professional website of John Myers, Ph.D."
  site-url: https://johnmyers-phd.com
  title: "John Myers, Ph.D."
  navbar:
    left:  
      - text: "Writings"
        href: post-listing.qmd
      - text: "Teaching"
        menu:
          - courses/25-fa-calculus-ii.qmd
          - courses/25-fa-analysis.qmd
      - icon: github
        href: https://github.com/jmyers7/
      - icon: linkedin
        href: https://www.linkedin.com/in/john-myers-phd
  # sidebar:
  #   - id: teaching
  #     style: "docked"
  #     title: "Teaching"
  #     contents: courses
format:
  html:
    theme: custom.scss
    header-includes: |
      <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;700&display=swap" rel="stylesheet">




